using System.Collections.Generic;

namespace VibeMap.Models
{
    /// <summary>
    /// Represents the analyzed mood and preferences for content recommendations.
    /// Generated by the Smart Recommendation Engine using local keyword analysis.
    /// </summary>
    public class MoodAnalysisResult
    {
        /// <summary>
        /// List of detected mood tags (e.g., "happy", "energetic", "relaxed", "stressed")
        /// </summary>
        public List<string> Mood { get; set; }

        /// <summary>
        /// Detected energy level: "low", "medium", or "high"
        /// </summary>
        public string EnergyLevel { get; set; }

        /// <summary>
        /// Recommended content genres based on mood analysis from Smart Recommendation Engine
        /// </summary>
        public List<string> PreferredGenres { get; set; }

        public MoodAnalysisResult()
        {
            Mood = new List<string>();
            PreferredGenres = new List<string>();
            EnergyLevel = "medium";
        }
    }
}
